[project]
name = "poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "autogen-agentchat>=0.7.5",
    "autogen-ext[mcp,ollama,web-surfer]>=0.7.5",
    "beautifulsoup4>=4.14.3",
    "crewai>=1.6.1",
    "crewai-tools>=0.0.1",
    "fastmcp[apps]>=3.2.4",
    "httpx>=0.28.1",
    "ipython>=9.13.0",
    "langchain>=1.2.17",
    "langchain-anthropic>=1.4.3",
    "langchain-mcp-adapters>=0.2.2",
    "langchain-ollama>=1.1.0",
    "langgraph>=1.1.10",
    "litellm>=1.85.0",
    "llama-index[lancedb,openai,openapi,workflows]>=0.10.0",
    "mcp[cli]>=1.27.0",
    "openai>=2.37.0",
    "playwright>=1.59.0",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.18.0",
    "requests>=2.33.1",
    "sqlalchemy>=2.0.49",
    "transformers>=5.9.0",
]
