[project]
name = "poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "aiofiles>=22,<26",
    "openai>=1.70.0,<2",
    "mineru[all]",
    "raganything[all]>=1.3.1",
]
[tool.uv]
# Only resolve for the Windows AMD64 environment
environments = [
    "sys_platform == 'win32' and platform_machine == 'AMD64'",
]
